language: rust
cache: cargo

branches:
  only:
    - master

rust:
  - 1.31.0
  - stable

os:
  - linux
  - osx
  - windows

env:
  - RUSTFLAGS=-Ctarget-feature=+aes

matrix:
  fast_finish: true
  allow_failures:
    # We still rely on Appveyor for Windows testing since it's more
    # reliable and performs better, but this lets us keep an eye on
    # improvements to Travis Windows support
    - os: windows
  include:
    - name: "Rust: stable (wasm32)"
      rust: stable
      env: []
      script: cargo build --target wasm32-unknown-unknown --no-default-features --features=soft-aes --release

install:
  - rustup component add rustfmt
  - rustup component add clippy-preview
  - rustup target add wasm32-unknown-unknown
  - command -v cargo-audit >/dev/null 2>&1 || cargo install cargo-audit

script:
  - cargo fmt --all -- --check
  - cargo clippy --all
  - cargo build --no-default-features --features=soft-aes --release
  - cargo build --no-default-features --release
  - cargo build --release --all --benches
  - cargo test
  - cargo test --features=soft-aes
  - cargo test --release
  - cargo test --features=soft-aes --release
  - cargo doc --no-deps
  - cargo audit
