language: rust
cache: cargo

branches:
  only:
    - master

rust:
  - 1.31.0
  - stable

os:
  - linux
  - osx
  - windows

env:
  - RUSTFLAGS=-Ctarget-feature=+aes

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - os: windows

install:
  - rustup component add rustfmt
  - rustup component add clippy-preview
  - command -v cargo-audit >/dev/null 2>&1 || cargo install cargo-audit

script:
  - cargo fmt --all -- --check
  - cargo clippy --all
  - cargo build --no-default-features --release
  - cargo build --release
  - cargo test --release
  - cargo doc --no-deps
