[package]
name        = "miscreant"
description = "Misuse-resistant symmetric encryption using the AES-SIV (RFC 5297) and CHAIN/STREAM constructions"
version     = "0.1.0"
license     = "MIT"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
homepage    = "https://miscreant.io"
repository  = "https://github.com/miscreant/miscreant/tree/master/rust"
readme      = "README.md"
categories  = ["cryptography", "no-std"]
keywords    = ["cryptography", "encryption", "security", "streaming"]

[dependencies]
aesni = "0.1"
arrayref = "0.3"
byteorder = { version = "1.1", default-features = false, features = ["i128"] }
clear_on_drop = { version = "0.2", features = ["nightly"] }
subtle = { version = "0.2", default-features = false }

[dev-dependencies]
data-encoding = "2.0.0-rc.1"
serde_json = "1"
